meta_product_name: "Talkeri"
meta_title: "Communicate real time like walkie talkie"
meta_description: "Talkeri is where, Staff, Useful information and Instant conversational tools come together to get things done"
meta_image: "cover.png"
# twitter_account: "@product_twitter_account"
